---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-config
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: metallb
      namespace: networking
  values:
    resources:
      - apiVersion: metallb.io/v1beta2
        kind: BGPPeer
        metadata:
          name: opnsense
          namespace: metallb-system
        spec:
          myASN: 64513
          peerASN: 64512
          peerAddress: 10.0.0.1
      - apiVersion: metallb.io/v1beta1
        kind: BGPAdvertisement
        metadata:
          name: opnsense
          namespace: metallb-system
        spec:
          ipAddressPools:
            - services
      - apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: services
          namespace: networking
        spec:
          addresses:
            - 10.0.0.70-10.0.0.90
            - 10.1.0.0/24
