---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ig-downloader-private-1
  namespace: download
spec:
  schedule: "0 2,14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          securityContext:
            fsGroup: 1000
          containers:
            - name: ig-downloader-private-1
              image: ghcr.io/tbrtje/instaloader:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /config
                  name: config
                - mountPath: /data
                  name: data
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
          volumes:
            - name: config
              configMap:
                name: ig-downloader-private-1-config
            - name: data
              persistentVolumeClaim:
                claimName: instagram-data
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ig-downloader-private-2
  namespace: download
spec:
  schedule: "0 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: ig-downloader-private-2
              image: ghcr.io/tbrtje/instaloader:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /config
                  name: config
                - mountPath: /data
                  name: data
          volumes:
            - name: config
              configMap:
                name: ig-downloader-private-2-config
            - name: data
              persistentVolumeClaim:
                claimName: instagram-data
