---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: instagram-data
  namespace: download
  labels:
    app.kubernetes.io/name: instagram-data
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-share
  mountOptions:
    - nfsvers=3
    - noac
  nfs:
    path: /mnt/tank/scrape/instagram
    server: 10.0.0.51
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: instagram-data
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-share
  volumeMode: Filesystem
  selector:
    matchLabels:
      app.kubernetes.io/name: instagram-data
