---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant-data
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: freenas-iscsi-csi
