# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rfAWGItNiAkLjtMdGLj6Zr2Doijy,iv:FrwWQh/m22sODz132oWFuqByprg1749IhLt7PvTNhjw=,tag:5U2mlF8PTKRmJKs4ghAshw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:OPPai0P+ESMTuURuQmSp/8hKidJJeunxlvqFDAyWdtxxCcePmA==,iv:8g8Q/FiacnQATisGbZdPCqJHrDxRok4QwdHLp2IiuUQ=,tag:qadpINkBz/WHXENprWTHLw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:O4xHQO6CxY5JelnqtYw+N0kxKA==,iv:tATRMjP0rjz+w4zCkgDEk+E/OsrxIo+fnG+PUENHQrE=,tag:YPxmMVfL3II6L7CV97Bqmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TXFya0RPVnRLbHFGUG02
            Z0NlS0VGWEdvQ0MyaFBKYUF3QnlFdGxLalVnCjBDTzM0eFlxa0tSZHRIK0RKTFQ4
            VDlyV1dlMWc3SHlNdHBOaE1vTi9Ic00KLS0tIDVIMFdTOVE4aUVOZUVGQkVpcytF
            Zm1EaG1LQ2J3dFN5amZLZXhuZ3grdjAKzXW9ZGwSWIk3PgVD7h9lnX8eN61M7DIV
            XNpFYKXM/iYD5bVtT99bbRgE+3//QhpBUPwSzNoe/PGl8HPPrMVOXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-30T09:14:11Z"
    mac: ENC[AES256_GCM,data:1vD3t8y8IhfeNy/38kSYg/PoUBlNkbtHy2s5AzzCdgh3iew6MDD3eJ3y0yrssazAPimSsBllUg2xaIU4xnh9Tyw2/wAd4S0s78w+i4a1uRITdL+MnbveCoUp+dCUAQ7BeJBBWHwdOkyWKcGylYGvaU+y/VC/gxF06Nbs3gWBl7o=,iv:9DVtZe8qLCbjr4oieL4cf5VcBFVXZry9W8oN+52oMlI=,tag:bPCNRVl2tsa3hAko4pBotw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
