---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: privateipspace
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.50-10.0.0.90
