# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:I8VEUyvd3PmU2ncA2R39G1w5J8HS,iv:VqQmNNb8aHWKXGz+YwAH+CY7mKYWFdYPB299FCRueVQ=,tag:kJchM0Hzkmnnf6ziz7ROMw==,type:str]
    api-key: ENC[AES256_GCM,data:LxKalH20NBInDDsh99EjFU3KT3xIzSaAYlqntkmZVrgzh6mhqQ==,iv:NX8GA8dP76hU3oubsiw7H0yyrZKFePHfDiSKlN8KRVc=,tag:OnT5rt+PXLymiw1a8PD+rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aG5HVU5KbjU1OU5ZTDBx
            OVdzbGp6dDVBZWNIakNiQ3FJRjRYeXhsWEdVCkYvTG9ZMjB6K1pncjNSTW1pUlQx
            WDhvUDBabDFvcU04TTNpcy9wRENKaGMKLS0tIGJLQnowekJ1SE9yQmNyalk0b3ZD
            RlR5U3V5aVRYalNCUHZBVXVWWExwVTgKmLWJuoT5I/khLTNMloakF5xHMGZJE5Ie
            I1GcxcTkvepaN37XRYRBf06/Gm1h6aTZ48i3OpXiyUE9qMXVDB/1Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-30T09:14:11Z"
    mac: ENC[AES256_GCM,data:wVdgi3GR58msseUTa4Kj2rppZYAlSSS8Ng1KuGRWI14WVPScJFz6U86tIfiFBRIwQ/lqUGUhThMaY6fiv2swSDce4fmB8wKsz57ohIr6WHCtnEKtMw1CPA0LWM3G+EzC8z4pVvIiyw/91IqWM6ZQojV8L8BAxkjUaJEaT5vO0Ck=,iv:NoSwHbVvNihRngXVYzOjCBMlmD14JZj2bK51R71fRvk=,tag:WfGJR2gY3ZUHpNfQknVYHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
