---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.0.0.70-10.0.0.90
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.70
  METALLB_TRAEFIK_ADDR: 10.0.0.71
