# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EmZH+DiekxkBH4DfFAc=,iv:Qy+9Zf7mSmiL/HWp8TF2lxWvv+ScjMiihIWHogjffVE=,tag:oy8eEmluAh5IfhJ/FY/K/w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Dl41Bq4qEDhElQMZzWPEgQTOORX5,iv:8olu5930Szd/xU+4hZomMK16HGQsngmwkhwEg4koIuY=,tag:ros1xHDYtsed5oeXwdC9qA==,type:str]
    TRUENAS_API: ENC[AES256_GCM,data:1KkKDgA9q2htJS1Mg+cp/oIapEWRwATWLud+55NvHx9m37IrnBTQmjk0Gzf6FCZEhkAK5QWXCTRmmS3WcI30L1PK,iv:u5kQU4ZRxvL5AUyLP75bLeKz7Ohv43eT7sivi1PntvQ=,tag:NMeKKQJusImPKbIGVNimYQ==,type:str]
    MQTT_ZIGBEE: ENC[AES256_GCM,data:l8EtNN/yVA==,iv:3Qw+X80EBMk+ropuRRcm6KECTMqifAwfbEkgeNyRkEc=,tag:pAHefFgTlc0hElkCoIB5+w==,type:str]
    MQTT_HA: ENC[AES256_GCM,data:tQHtFE4QHA==,iv:zcWnLzBV4p5puFpWIIcCs8bfUqizGPBCGVro2Toc8Vo=,tag:9vWYq2HMLHIYJwBOkUjMsg==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:SvEv+H4l0+g6rJmdiQYmO9L2K3c=,iv:8zyqHgCnkK+M5cbIg+dUBzmc0rlfkdISDRicJCxjZVA=,tag:NA+je6Xz77zBa0Mcba71sg==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:6T5ZgaQLaVzWlO6ETdPyUTuYlUuR/+Shlgk4Q9y2ckg=,iv:Z3XJ+hutumnpWm88NEHLdT92xzFnNUomk4iPFKCpKTs=,tag:HULbdvoctuRL1esGXhzZIg==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:HTRygc1X7W+HIsUvUtP5L4WR1TbbPBQVarN/M19vutc=,iv:3NtgPcKje6x1xai/ngtw/p52dz5gAUC2m9/V9edJIzo=,tag:bPyvs7yO3grGOf+sd7z43w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Njgvxa+Epco=,iv:gQApLOPpDfqMN6jFRKPcVNnUwooGHZEuWyJTDeZh4CM=,tag:iF+/Rp5hr6bNWkuQw8HKKg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:+JHGVz+GbQs=,iv:qKWKli9WYZvcodK33Wg3dAwnCbT5KQwOhFZ2DHXY1+A=,tag:hXZX2JkFWUnZzjEH6nedWQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dW2hxmqOz07JlUBvrTF71d1o9KgaFdfZGX4l/qKHLEg=,iv:ZsDR7trWSFGwLkjxMMF9gWd5Kj1zR78fbMyyf0TBmz0=,tag:FZ5qBdzZJbD5tO8vdeTouQ==,type:str]
    BROETJE_ONLINE_SIGNING_KEY: ENC[AES256_GCM,data:abJ7ReZ3AodDNWUa9jqoFLVnSk2vkW27xcbnyinUlDu8TG0Qe6q9UzE90gVuaW4djBnmFGawZG+dFQ==,iv:H1sHu2xJErRkj+3rfhIok6WLbUB3gaPCwI4j4ZxDk4s=,tag:jWRVT/8M9ilzpXfG46GKeQ==,type:str]
    BROETJE_ONLINE_MACAROON_KEY: ENC[AES256_GCM,data:Bw5egu/STrvC4JRH/gKXJHaFImhfvkiZnrLNTnHP+eIDe9KJTbNWs5fVvVSszqhSNRHDovG/nPseSCcVnuO5gg==,iv:iEJIpzvAr24rd7s/yp65yRQ+ktyfzpYvvofyYr+RA/g=,tag:fTZV2ZE3Gt9Ad65Jt3c6IQ==,type:str]
    BROETJE_ONLINE_REGISTRATION_KEY: ENC[AES256_GCM,data:OkYfYN/UAdRUQWnzZtkXBLU3SyRUQhwDhfQs80d300R5q4U8Szi5fV8ZAApMAPHcthRVMPdr2GK71TaEnjV5Cw==,iv:bH5KbpVRWzlOYV08COzYRduEwVb//bLvaAHYnFV95AU=,tag:qLyCn7TSRJ7I2e2zAAEiEw==,type:str]
    SYNAPSE_DB_PASSWORD: ENC[AES256_GCM,data:GoFSxy7ST5AjFNbPs2pTZXzCPKW6/5RrwSyAIsc7JJ0=,iv:6ZmurAims8QTr2iUji5NOFvDPMizCzRlUe0V/mbTQC4=,tag:SWWqf6yraeVofN5raj8KmA==,type:str]
    REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:e+7sSIhwE3PcbIHjcO+QL2hGg3YJycXDIJ0V6xXAqtA2v4uGNyp7L9TmnhLMgMIG6/nTeeWnDL6LSGDDWbwIDQ==,iv:lCgrr7uSMulEFen77fPbe5i9u3J3tCZ0u9lCDc/qR6U=,tag:2hW4QaFMQE1Cev2aSJyhDw==,type:str]
    MAUTRIX_WA_AS_TOKEN: ENC[AES256_GCM,data:iIKM3KnJcTIQTru52IdKVbg971ibk+VbVLZACYbSZXurW54DKG2Q9xJFeEAsy2fjIDsifnNeVbwUSUKPw71qmg==,iv:5SZZMdSGo40R+hr+FgyNDPGG2C7SO0cDXZqozYOauKo=,tag:wlPrNei3lhR+AZ0mTnt3cA==,type:str]
    MAUTRIX_WA_HS_TOKEN: ENC[AES256_GCM,data:SmCnuiLBWYE7umVEkVVsUov9G/h4W0wPxRGvIBjYnL2r9IquJ3qC50ILb6FpRcWNDzBWGrbK+Ga5fQ8KXmLvBg==,iv:APMoVHR7LAaHgYkhoTDI0vkOr8ZKQodY295FWuT1tAU=,tag:W+MQE9oVsa0m04CmaEQGQQ==,type:str]
    MAUTRIX_WA_SENDER_LOCALPART: ENC[AES256_GCM,data:E3aYeDKTkhi2BnofZNc3+eymvJ7nmX2oozSJXzBjjFc=,iv:WUtFiWogj+HRRuHzcYSETRjevfYHNfk8TGJNGc0WO8I=,tag:w3CstIXOzW50VrRBTtQvxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK1dBSy9ZWHdhbzNuYXBu
            MWhFZmQ3YzRnRkZHc3BoV3lNcGhIMUk0VzFBCmY3VnhCR0I4M3hBYXRzTnFBSHJo
            aXF1L1JhMnRNVmlRTU9CQ3lPeXovNzAKLS0tIFdFNUFrNlNJOVFEdzkvaDk0cEpY
            U204UGR4V0ZEZVAwZnd5TWFJZ3VkWXcKAKdgLxeDUwBvBl2PlXqComKrruYGNXLo
            BHoRRSnzOVr+Xy/LFlYW2W+VADXzJtemwvOHBdZz8hD/lQxw7KKw5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-18T19:53:20Z"
    mac: ENC[AES256_GCM,data:avg8zCCW3oxZPIKPf+f3LvmdYJ0q6dUVKuh+m9v1RxWmMmQPzaEU4yZRBYrE8jwA7uzbsTj1N89wJf+tHnkJJRcb7S5QYQM1fyVEyowPxnp+Wniq9TefWCiOSw1NakcwF1Dr6SrWbmaZXaH4E4SOVQUBoR0Au4+I2gjhS45P37k=,iv:BnpxOBefnlLRERWCHU55FBW1MBWX/MK5WzGp5VqM6iM=,tag:Tkolfdtxezh1P316SLdsbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
