# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ia7x3FJfFoDmgPwa/FM=,iv:Ej0H8s8JHxgSlMutt6eTwIxOWs5i6K5PTB11Vj8LggE=,tag:IUCOMCayVCj8OXWQHEaBdw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xeLKABdHaMGz3IQFM5/EgCkvnKEB,iv:Krbq2mZ43/GkzTu1l+8ZfI6ixoYIZEXtYrC9OMhHV0A=,tag:Y1qFM/cN9ewP318YCqfdDQ==,type:str]
    TRUENAS_API: ENC[AES256_GCM,data:lG8eG/IRS3AsQM5oqHVW55Yzxl/u/NCHKrzb1z0GHfRjOPWsAq3Lvg+mmK5/Vwq0B8dPdJbZMduOsZvpFzGFDnA2,iv:cZwuN4axMUktwxI0+ctM60DBp81bGi9upZFrqFRcHKU=,tag:DkGxgonwn1ATcEXtH/x2Sg==,type:str]
    MQTT_ZIGBEE: ENC[AES256_GCM,data:gcql9iJJEg==,iv:TgK9z97i1Y7LFLOH/mUBdKYVpPDfFbS3NA4lPZmdIEU=,tag:vVsbR6d7JfIeFG17/YNH8w==,type:str]
    MQTT_HA: ENC[AES256_GCM,data:OPvs9cWz9g==,iv:lq0gRz4MBV6SEFqSl5RURuMYpnKvoV8yW0BTPnMVZOI=,tag:PKaF0GrvrNl1nsHHMeBE+Q==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:LZ2TtYeu0KFP2kGdPs9tiF7poeY=,iv:k8Nv0zLfDph0+eL1cHuAGauOWvr0Ke1ODfPbQhKA/Jg=,tag:DCEAQmJJ+t6Le35V1NyScA==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:JD+D/oabLuMpPU/derm6xwDL8u2tquIu1jNK1SwA8UI=,iv:L1jR2Z/RRcQUC+InCyCuF4KvwgddwopaCtSYHbNTxO0=,tag:VF8P7swB5Oj+NCHnWZPuEg==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:yioGRt8cuUiyO5RlSovTiehqQXBspAs7ceI0urAyO4E=,iv:DAQOqA67wWT3zLXm/zvs3M8qvCYIwEE0cQYcfEj4UQY=,tag:1hqRQhW39wVoLtIUE6SjOg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:FqWyM8yNVpM=,iv:sKPrMVSJEHAzVgU8/u+6httBnYGLlvy8wF3P7aJJiOA=,tag:ivy6PQwNsfnr8P4sEbgspA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:gRje96Ttj0o=,iv:GJ/k4YDZbo4UxcvrtraUTBVWeJc6WHGZcWFibIXjVBc=,tag:XnuFzrgRTsiHceCMCGCPAA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Kr675Adi8pox2VsYFmUzoXYOwybYRcfe1zt1b2DYKPQ=,iv:iCfQioJ4DW8ENYrkvezVos+zkuJLiAlwTLfWKjHo4dQ=,tag:E78gMarlFok6mnrXP5PlKw==,type:str]
    BROETJE_ONLINE_SIGNING_KEY: ENC[AES256_GCM,data:GtHyNAQiPtOh+adABv3BskOGKG2J0tjPzMVuewAsdA/PuqxXYmUNUHMB4Mt7UPzH1um4YLc0A+nqhg==,iv:lhRWie/70AvD+1i8rPNDHuR0zzPNvqJ/KfdEqcZar1M=,tag:Wszr7wSFl0tuwvOt2iPW7Q==,type:str]
    BROETJE_ONLINE_MACAROON_KEY: ENC[AES256_GCM,data:jW533ksDs6W/7/bOKwVOlNkDv0GAFbVByxojgu8x9T3oLtmtXgNh9TVTGbN0PCb3PM/IZRGwVwRgCuWcrrtF+w==,iv:CwaF+juyNaY2b5kXrpUCg3omnhLRWp+uyyPf+w7qKcs=,tag:poGj+1oLCTimJrLqccig3g==,type:str]
    BROETJE_ONLINE_REGISTRATION_KEY: ENC[AES256_GCM,data:f2g8sZsN+bs9h6gbE7yv6u/v1/5fmYamlMQlv/CqQm/SHwj26OQZSI4D7iTwsk2cAiTlpZupmMD50EmZ9d78Jw==,iv:4bb88a2G06vQHtbC2yMp4vkGM666q0eqdJ6p9gpdHwE=,tag:UA0ioF4Eed/H/+AvM/8YDw==,type:str]
    SYNAPSE_DB_PASSWORD: ENC[AES256_GCM,data:mlViZxyqt18iuP5QwHTWxVhRC6xyKb4qhi2ClI0nfQQ=,iv:iyTnlhWpj+gx/T6upeHY8e2u14BXQQrIXWoxVb7dh74=,tag:LeZbcOhbg24S/rT4UHwnHw==,type:str]
    REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:KTdsReM+M/O8a5r6+1AqNxrwL6RN6EEwtyPKghQqz2GZOknqktGGW2Qji8QnfdcVz1x1c4SOiHNBNcR+WR0vtA==,iv:/n0+iBeS25oE0ngfRqtkPcmXV0SLLK2bh56w0N+Co4A=,tag:+h3hD8fe/IfOkHGKCeIbaA==,type:str]
    MAUTRIX_WA_AS_TOKEN: ENC[AES256_GCM,data:Exdhojjr59tt2eml3KFrJzxZUOGKKcaZb9KPtIhF+mFks7+zt9eJlfxrmk0jn/dCS0evCpmt95GXNL2zOZY21g==,iv:ZwaGO11O2cBTFesBrfKBqqF3R6jfsY/wpiCi4x3wZX8=,tag:FYsSGUzKh9+0kM8NesWUTA==,type:str]
    MAUTRIX_WA_HS_TOKEN: ENC[AES256_GCM,data:Kjqk7kxbNtyf06DvOUcdguyAg6K/8CNyZtCmVit9RqLysHOaaxfdRzI9unKjUsJ3aqjveB4dMGkSxr8QsMFQQg==,iv:lEb8oSmLuGqwOeQ864KLas8b22/gSL55KPnqCrZMoQY=,tag:aO+HV9aX0ZG5scN92RnSQQ==,type:str]
    MAUTRIX_WA_SENDER_LOCALPART: ENC[AES256_GCM,data:/sO8q004xHgYewlPOaH2u3MlQzkgHCG69a2nctgNsGA=,iv:S2jLiMV2ZQEZkK+yWbNUgEA9rceFFp1zOWjHmym1wxk=,tag:dc5jT7Vh48C8ujEwA8lq1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV2ltNldtbTIyQ0JXdjhC
            ZytYWVNDcUx5dUxRb3NXRUxiTTZwRGk5UERnCnM2UjJRSlpuZHlkOVJxN1h3UUJl
            RVZtVnRPYmhIaHdSTDZBRmVaaDJzWVEKLS0tIEdrUkJVeUswalFlME5vNVZITU5h
            d0N3QlVaQ1RkWWxOdXU0R1EzM3RXY2sKQ447C9tE/uQpF6TxM81D06Z0sRl1jxQx
            o0s8CQkukKSQpt4msmPC7kZKwembMMG6qoKwr8r3UjI2+ZceInd0nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-19T19:27:09Z"
    mac: ENC[AES256_GCM,data:0XZ3ZVhHz8X6ecQrXlSINFhNh+wxmAn91UhK+yyES+SQ5MjBoqAxlbb44+G6A2HQkcF7yLV2PDMM2SBLm05yjSg6kaTQwhxENAUVJf/Td/xvFHEXI8hGDYjh1iuOsKZHqrQpS/MJBVNbE3F8yiaA6/WZ6l3y/r+znYsLZcFbvyk=,iv:difNHBRd0hP0NmaIE1fwgLNt/82Iz8D7ssyUKgOrmjU=,tag:1sCQhOQAsgYOKnnj2cZY3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
