kind: Secret
ansible_user: ENC[AES256_GCM,data:f75gLKs=,iv:gJtezmzVMz0nFL+sCIM2YUhEI4nXsIXHtroAHfL+9cI=,tag:qywSZoGg+iUJB7Wh2o6q7g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jRB/bVrv6A==,iv:HmXcCH5rXF7XKOm8FGMrH8HoojkX7K97FsAejyIO2Lc=,tag:GWpScyZoLakyIw6GaNhmKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMFZrdklJdjgxaTI5MTVV
            a1k5Mm9WUlhUOGgwMDVjN2hTTjNwMG03K2hZCk5Sc3lkeVFYTlhlRWYwdGFLSGdk
            bUFYbDJ3NWdFclVyMTZaNWZuSHEzSjAKLS0tIGNKS1RlVThVU00vYzZLaFR1czd5
            cjRwVytSZ0tKVUNVOFJIRzZxZG5Sb1kK3b05YT5B9UVEbqm9BCdJksxpOlXaWmb7
            jcsjIOQ4jlNmB2B5cPbHd4XozsZ8UQu4XgtuvKzz1TZG4AxR2b8iMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-30T09:14:11Z"
    mac: ENC[AES256_GCM,data:vuuq0Jf2CFa/QaV7dRA0Mlyd9pDFjbeZXQirm50z804lxnG8qaRGHtDVTSxXl6nlI+qsRIFQTOApBfyQcRA8VGHKu+DydqYyewZHOXco1tffGo4UGVCl37Jf/S3OKntyRJW+VvDz/2n+bujk/Xrt8MEH+pLSU7wj9LuYstSoDjc=,iv:ZdSe7Zy1nJMjcjUzrn30KWA9HqNb/doopnb4A9FwQj4=,tag:DTK4c+FkT1euDQ8Oo+0v/A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
