# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gpyeP9Aa6RAZYTHIpj0=,iv:CVtt4o5sVIZJnZPaEatLkgW1sCwGm2u7sEIEGJ1PehA=,tag:872UUhAu4e7hRW07NAdT1A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:EORdCrzoWqGHU7xLpdIPjBuRSgAH,iv:1hKumaK+uaWAT/mZlHWxRwZ1nFywf9zhRQnA8WXnPaQ=,tag:RakmRK1jDx7X65UUKv0yXA==,type:str]
    TRUENAS_API: ENC[AES256_GCM,data:2R6dF26AW+Dl9cto0kOR8nrYda7BRaWCBrpBMVfgXP2WWKZvMbTMXsJgAmAwGmd45mnrV+UdOGqgBpxoVtqDaAYr,iv:w4+Sio+E3FQ3/HgLGYbYwXaMEvNPEcKuvFGZHgKGF4I=,tag:In3wUBkONeg8xpFRQuy8yw==,type:str]
    MQTT_ZIGBEE: ENC[AES256_GCM,data:F4lUMEclxw==,iv:5kcRfw8OJfXUewHPvqd+Vsiaq+xFOeNOb3ziwejrJ1o=,tag:h1toLF4E4+I9NzfHL353Og==,type:str]
    MQTT_HA: ENC[AES256_GCM,data:nbLsGQKYeQ==,iv:YBM8324awPuASl1RDrK+ajt+lUEA3TwfreBphNgZmHk=,tag:w2GKCUU1EFtGk5RKUnbKXA==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:vnM0NMz4vGLUDFqdRk+Y9mwvNjE=,iv:jikOoVnx2BmBQk4ZTRS2cjL2NRhAu5kY4iaRtffx74Q=,tag:ecakeeyR5Tx6KbVPEeBDpQ==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:eRa4ijn5Sg0xQXxc1GHq9q1QcCVYRuJRcxXY1sS73fY=,iv:mC0adjMCRBeKuD5wBzOwMqvQINvr22CaIp+u1msF86c=,tag:Etfxx7dw1Kw5bMvz1mpO4A==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:k7eVx1Lz+5JscmhK6IGoyreLk3z2fNqjR3QwZzKTkgk=,iv:Gat3mZvdRiTUHYc3z0eokkTahTkDRX7PmL/tPpsWvUs=,tag:6Yn9HhZiHlu2oxRniQUugw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:VFlLJ9Hv/YQ=,iv:xSuOKrlBGAlBrEFyeNrqBjrmyQ8VJd1iyS0JbHe27DY=,tag:ycBkn9AYWT9ZufDKAutPOg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:gKZWDBMgmEo=,iv:wMajRMzZ35UfiAYDXuqj8TAR5nHnu/DJZ84isib9/8M=,tag:vvV7nyun336Qfg6RDs2hQg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gDmK5CQEA/qOAcisKt3yTDn0Ohf70MYr/Tkf92fTImI=,iv:Yfbt97XqvXpFmkQQUbl+WkhCc/1M0TyD40VYaL2x7VU=,tag:mxlFrKm24X5AFe+zriyDQg==,type:str]
    BROETJE_ONLINE_SIGNING_KEY: ENC[AES256_GCM,data:dR2ifTmFJCSc2BIapCnp4Lj6zXV+KwXXjw0OH49QZL5/QQxXb3Wod3SVIm78ErEK5LZJsBULCY5LhQ==,iv:+sg7Oqbs3ceFsEWij8kRxievRMyitUPTxNGOauVSdJ8=,tag:xf9oAaqFdKL7iYYVkaJgaQ==,type:str]
    SYNAPSE_DB_PASSWORD: ENC[AES256_GCM,data:uCLqmiGFwVhTWnIsJ3Z9kqUtCV8mUO+GBAG0VH/bKaU=,iv:A9d798aF/gFVjtiDh2A3S2IrVl9pUX6t8txe3ipHzFU=,tag:uIDviAQzta4zeQMeSeBIRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbDRBYmMyczNyWlhWbjZT
            R29RMFc0TlNwREJMZmNIcFJscVBKdEYvcFF3Cmx6WldpVzk2aW9KZDJvMXdKTWdm
            bFAydEg1QUhjY0xPTHltcXlheDlrZGsKLS0tIHNUbEQ4NTVZc3ZxYVdzRVQ4dU9Z
            VTUrNndnb0JrUVFtN0hvVzZYcFdxNDAKPgTbhUEUVMu3xkbYeEdrUVu0GH/o2Vu6
            IyiUri52oVjpERNxiVwrJFK2CErE5XG6Xo0JrCeVg9jG0xS/vjpbhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-13T08:13:12Z"
    mac: ENC[AES256_GCM,data:F24snN1aobpqmzg4YzaLXMKmePSgDGMEAAjFheQCqGYzSOLiPoFgmQU265wUuTPYCKrB0EKJp4F4ykP1Pd6m5pyaWo20LgtX+Y2PgYslkss3nhZ2tEOk3PrtSLRGz+CUX95qNeSC8M+gm7bb7ARAmSA72p7b7vEROs5zXRobtX8=,iv:nxSENrp4OZ7DvdeDMtkU5fsr/B3PRkY4c6spkqdXgUk=,tag:zEI/VN/B7Nvzf5N1KSIhQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
