# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HL03MpTWlmyiQPSLw/g=,iv:L8LfXJgE2HkIZms6JGKYBCeCQUvVhPX/F3b/OcOTuI8=,tag:CvigNR5b0OQXLRymcB+DXg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OqNacLjCpZhkXChdS7767pLKW+/w,iv:YXjFfvMwEviiLwjd99KkZmf5MvMcLRq6gLoeeEq9Pno=,tag:mVylZD/HaPrhErJN6FWD/A==,type:str]
    TRUENAS_API: ENC[AES256_GCM,data:aUH1kG0fBUf/y9I+IQKLtwNViCN/Q65jtnnwh3RTmTt+ROTZu/TZzX04TyBE9CM8RheiLsqqlBmejGR+tFtr5nrY,iv:ZMflhk+mAMGGXK4LElHEfNyF3Es77G/rgm/kE29JavE=,tag:sHSbmKUmsflexmVb9cn8sw==,type:str]
    MQTT_ZIGBEE: ENC[AES256_GCM,data:lUfGNYbB1w==,iv:eHxXyeFV6i/H3GFkE39fRNNu2KvLN1teNV/+FrqGSyY=,tag:OccU0GDWYwAn9zZPTb2WaQ==,type:str]
    MQTT_HA: ENC[AES256_GCM,data:MN33TGhJPg==,iv:1LQKMtNfi0iRrRU0vphn5ncZxXpbgHRY/QaicUdJufg=,tag:nah/psY7GKUr2OvO8sFAWg==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:QjcG2etLrMcNHILHFweSdgvv1ZA=,iv:DVwvhYf+RFrP/AQWG4U469ip0xEw7hqCtvQo5cvow7w=,tag:oMEkLW7EoztNKXv8CawVtA==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:uTjiX79sPt8TdGKJ8hqn6HsghnEsFDbKCiUDywnzpjY=,iv:Lmw9MkiijAYylVnxLcN5wd+w14PBH4luPGlTCjQB8aA=,tag:TysixzpRA6eKDpimoZ2rqA==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:x0BZ6AWllkTpcs3JWfADzyoiuFHpKcMezLQcyzzsPjg=,iv:lhLQmzW9enlcc3D1WofTqsDfb4soe8mziZHGSu1uir0=,tag:MADvxfOtRQEO9HCecXBQCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YmgyZVA4amdIa2tYL1lu
            YU5zaTJVOEN0aTExNUFMU2o1dFFJT2ZVOHg0CkNnQWVXMmM2WnhKVVlQMWRKNHhn
            R0lzNVJSaW50dDdUTUw3aGhpUDlOQWsKLS0tIEVSaXZxZTh5TzArSTExQUtvajUw
            MW9VcjlXZjR1NURRVWp3Yjg5OHJSd1kKPXlykAqiKh0MQnnraLii4fZ5B7iMiPs7
            yQnYUWg6mn4PdYAn3tKunIM/nw+PBBfN0FBnvHRzBeKCmZbt+wdoGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T18:09:57Z"
    mac: ENC[AES256_GCM,data:0ta/l74A+1q2Olm9B35NYDN3+v6hMlPESHJ8mzHZEAoJff8dHkNxJaGGsvwIRvCRDl3SDeJx1BIkrqQVYMD76MjLeeFiZ+5V7hhty5euY+lgwm8gShAMq7y8HlqIHLFVkim59bawiOwC1+LknWWjzqaz8Z0yDk1YAEotOh/ffJY=,iv:htMb/SfnjYAoq82gGAdyDxn0bHS6E3Lteq96fwrpujk=,tag:oQZlxX1puK+lo5UwvCTwsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
