---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: esphome
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: esphome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: esphome
    spec:
      containers:
        - name: esphome
          image: esphome/esphome:2022.12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6052
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: data
          env:
            - name: TZ
              value: Europe/Berlin
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: esphome-data
