---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: esphome-data
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: freenas-iscsi-csi
