---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: db
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: democratic-csi
      namespace: democratic-csi
  values:
    resources:
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: postgres
          namespace: db
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: postgres
          template:
            metadata:
              labels:
                app.kubernetes.io/name: postgres
            spec:
              containers:
                - name: postgres
                  image: postgres:14.6
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: POSTGRES_USER
                      value: ${POSTGRES_USER}
                    - name: POSTGRES_PASSWORD
                      value: ${POSTGRES_PASSWORD}
                    - name: POSTGRES_DB
                      value: ${POSTGRES_DB}
                  volumeMounts:
                    - mountPath: /var/lib/postgresql/data
                      name: postgres-data
                      # postgres heult sonst
                      subPath: data
                  ports:
                    - containerPort: 5432
                      name: postgres
              volumes:
                - name: postgres-data
                  persistentVolumeClaim:
                    claimName: postgres-data
