---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  namespace: db
spec:
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
