---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: db
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  type: ClusterIP
