---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: synapse
  namespace: messaging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse
    spec:
      initContainers:
        - name: synapse-init
          image: matrixdotorg/synapse:v1.62.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "cp /config/* /data/"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
        - name: init-db
          image: postgres:9.6
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgres.db -p 5432 -f init.sql"
      containers:
        - name: synapse
          image: matrixdotorg/synapse:v1.62.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SYNAPSE_SERVER_NAME
              value: "broetje.online"
            - name: SYNAPSE_REPORT_STATS
              value: "yes"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          ports:
            - containerPort: 8008
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: synapse-data
        - name: config
          configMap:
            name: synapse-configmap
