---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: synapse
  namespace: messaging
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse
    spec:
      initContainers:
        - name: synapse-init
          image: matrixdotorg/synapse:v1.71.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "cp -v /config/* /data/ && chown -Rv 991:991 /data"
              # This is required for Synapse to work properly.
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
        - name: init-db
          image: postgres:14.11
          imagePullPolicy: IfNotPresent
          # TODO: Figure out why this does not work and why its not connecting.
          command:
            - /bin/sh
            - -c
            - "echo connecting && psql postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.db/${POSTGRES_DB} -f /data/init.sql && echo done"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          securityContext:
            runAsUser: 991
      containers:
        - name: synapse
          image: matrixdotorg/synapse:v1.71.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SYNAPSE_SERVER_NAME
              value: "broetje.online"
            - name: SYNAPSE_REPORT_STATS
              value: "yes"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          ports:
            - containerPort: 8008
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: synapse-data
        - name: config
          configMap:
            name: synapse-configmap
# TODO: Create the well-known for matrix
