---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: synapse-data
  namespace: messaging
spec:
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
