---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mautrix-whatsapp
  namespace: messaging
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mautrix-whatsapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mautrix-whatsapp
    spec:
      initContainers:
        - name: wa-init
          image: dock.mau.dev/mautrix/whatsapp:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "cp -v /config/* /data/ && chown -Rv 1337:1337 /data"
              # This is required for Synapse to work properly.
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
        - name: init-db
          image: postgres:15.4
          imagePullPolicy: IfNotPresent
          # TODO: Figure out why this does not work and why its not connecting.
          command:
            - /bin/sh
            - -c
            - "echo connecting && psql postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.db/${POSTGRES_DB} -f /data/init.sql && echo done"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          securityContext:
            runAsUser: 1337
      containers:
        - name: synapse
          image: dock.mau.dev/mautrix/whatsapp:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          ports:
            - containerPort: 29318
      volumes:
        - name: data
          emptyDir:
            medium: ""
        - name: config
          configMap:
            name: mautrix-whatsapp-configmap
