kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
  namespace: media
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
            - containerPort: 8920
              name: https
              protocol: TCP
            - containerPort: 7359
              name: discovery
              protocol: UDP
            - containerPort: 1900
              name: upnp
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: data
            - mountPath: /media
              name: media
          env:
            - name: TZ
              value: Europe/Berlin
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jellyfin-data
        - name: media
          persistentVolumeClaim:
            claimName: media
