---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: media
  namespace: media
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/tank/Media
    server: 10.0.0.51
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  resources:
    requests:
      storage: 8Ti
  accessModes:
    - ReadWriteMany
  volumeName: media
  storageClassName: ""
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: media2
  namespace: media
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/unimportant/Media
    server: 10.0.0.51
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media2
  namespace: media
spec:
  resources:
    requests:
      storage: 8Ti
  accessModes:
    - ReadWriteMany
  volumeName: media2
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-iscsi-csi
