---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: "jellyfin"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.57
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
  selector:
    app.kubernetes.io/name: jellyfin
---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-udp
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: "jellyfin"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.57
  ports:
    - name: discovery
      port: 7359
      protocol: UDP
      targetPort: 7359
    - name: upnp
      port: 1900
      protocol: UDP
      targetPort: 1900
  selector:
    app.kubernetes.io/name: jellyfin
